version: '3'

services:

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha_backend_rust
      - POSTGRES_MAX_CONNECTIONS=200
    volumes:
      - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/script-01.sql
      - ./scripts/dml.sql:/docker-entrypoint-initdb.d/script-02.sql
    ports:
      - "5433:5432"

  rinha-backend-01:
    image: odairft/rinha-backend:v1.0
    container_name: rinha-backend-01
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:123@db:5432/rinha_backend_rust
      - PORT=3333
    ports:
      - 3333:3333

  rinha-backend-02:
    image: odairft/rinha-backend:v1.0
    container_name: rinha-backend-02
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:123@db:5432/rinha_backend_rust
      - PORT=3334
    ports:
      - 3334:3334

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha-backend-01
      - rinha-backend-02
    ports:
      - "9999:9999" 

networks:
  default:
    driver: bridge
    name: rinha-network